USER_CREATED_SUCCESSFULLY = 1
USER_REGISTRATION_ERROR = 2

WALLET_CREATION_ERROR = 4
WALLET_CREATED_SUCCESSFULLY = 5
CANT_CREATE_MORE_WALLETS = 6

GOT_BALANCE_SUCCESSFULLY = 7

TRANSACTION_SUCCESSFUL = 8
TRANSACTION_UNSUCCESSFUL = 9

INCORRECT_API_KEY = 50
