USER_CREATED_SUCCESSFULLY = 1
USER_REGISTRATION_ERROR = 2

WALLET_CREATION_ERROR = 4
WALLET_CREATED_SUCCESSFULLY = 5
CANT_CREATE_MORE_WALLETS = 6

GOT_BALANCE_SUCCESSFULLY = 7

TRANSACTION_SUCCESSFUL = 8
TRANSACTION_UNSUCCESSFUL = 9

INVALID_WALLET = 10

FETCH_TRANSACTIONS_UNSUCCESSFUL = 11
FETCH_TRANSACTIONS_SUCCESSFUL = 12

FETCH_STATISTICS_UNSUCCESSFUL = 13
FETCH_STATISTICS_SUCCESSFUL = 14


INCORRECT_API_KEY = 50
