USER_CREATED_SUCCESSFULLY = 227
USER_REGISTRATION_ERROR = 228

WALLET_CREATION_ERROR = 229
WALLET_CREATED_SUCCESSFULLY = 230
CANT_CREATE_MORE_WALLETS = 231

GOT_BALANCE_SUCCESSFULLY = 232

TRANSACTION_SUCCESSFUL = 233
TRANSACTION_UNSUCCESSFUL = 234

INVALID_WALLET = 235

FETCH_TRANSACTIONS_UNSUCCESSFUL = 236
FETCH_TRANSACTIONS_SUCCESSFUL = 237

FETCH_STATISTICS_UNSUCCESSFUL = 238
FETCH_STATISTICS_SUCCESSFUL = 239


INCORRECT_API_KEY = 50
